#! /bin/sh
### BEGIN INIT INFO
# Provides:          gwss
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: WebSocket Server
# Description: Start WebSocket Server daemon: gwss
### END INIT INFO

NAME=gwss
DAEMON=/var/www/bin/gwss.py
USER=www-data
GROUP=www-data
# Exit if executable is not installed
[ -x $DAEMON ] || exit 0

DIR=/var/run/$NAME
PID=$DIR/$NAME.pid
RETRY=TERM/30/KILL/5

# Load the VERBOSE setting and other rcS variables
[ -f /etc/default/rcS ] && . /etc/default/rcS

# define LSB log_* functions.
. /lib/lsb/init-functions

_ev_ () {
  [ "$VERBOSE" = "no" ] || eval $@
}

[ -d "$DIR" ] || mkdir "$DIR"
chown -R $USER:$GROUP "$DIR"
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    _ev_ log_action_begin_msg "$NAME starting"
    R=$(start-stop-daemon --start --make-pidfile --pidfile $PID --exec $DAEMON --chuid $USER:$GROUP --background 2>&1) \
    && _ev_ log_action_end_msg 0 \"$R\" \
    || _ev_ log_action_end_msg 1 \"$R\"
  ;;
  stop)
    _ev_ log_action_begin_msg "$NAME stopping"
    R=$(start-stop-daemon --stop --pidfile $PID --signal TERM --retry=$RETRY 2>&1) \
    && _ev_ log_action_end_msg 0 \"$R\" \
    || _ev_ log_action_end_msg 1 \"$R\"
  ;;
  status)
    ## return status 0 if process is running.
    status_of_proc -p $PID "$DAEMON" "$NAME"
  ;;
  restart|force-reload)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
    exit 1
  ;;
esac
